<?php /** @var \Devotionalium\Block\Devotionalium $block */ ?>
<style>
    <?php echo $block->getCustomCss(); ?>
</style>
<div class="devotionalium">
    <h2 class="title">
        <?php echo $block->getHeading(); ?>
    </h2>
    <?php foreach ($block->getDevotionalium()->getVerses() as $verse) : ?>
        <div class='<?php echo $verse->getBiblePart() === 0 ? 'ot' : 'nt' ?>'>
            <?php if ($block->showOriginalLanguages()) : ?>
                <p class="versetext original <?php echo $verse->getBiblePart() == 0 ? 'hebrew' : 'greek'; ?>"
                    <?php echo $verse->getBiblePart() === 0 ? 'dir="rtl"' : ''; ?>>
                    <?php echo $verse->getTextOriginal(); ?>
                </p>
            <?php endif; ?>
            <p class="versetext">
                <?php echo $verse->getText(); ?>
            </p>
            <div class="reference-link-container">
                <?php if ($block->useLinks()) : ?>
                    <a class='reference-link'
                       href="<?php echo $verse->getReadingUrl(); ?>">
                        <?php echo $verse->getReferenceString(); ?></a>
                <?php else : ?>
                    <p class='reference-link'><?php echo $verse->getReferenceString(); ?></p>
                <?php endif; ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>
