<?php /** @var \Devotionalium\Block\Setting $block */ ?>
<?php $setting = $block->getSetting(); ?>
<input type='hidden' value='0' name='<?php echo $setting->getId(); ?>'>

<label class="description">
    <input name="<?php echo $setting->getId(); ?>"
           type="checkbox"
           id="<?php echo $setting->getId(); ?>"
           <?php echo $setting->getValue() ? 'checked' : ''; ?>>
    <?php echo $setting->getDescription(); ?>
</label>
